### ISSUE TITLE
BubbleKern UI Stopped Launching [Glyphs v3.2]

### ISSUE THREAD

**Issue by thommilson** [Tosche/BubbleKern#12]
The UI for creating kerning strings and running the script seems to have stopped working on the latest version of glyphs.

**Comment by thommilson** [comment]
This is the error I have in the macro panel:

NameError: name 'NSMutableDictionary' is not defined
Traceback (most recent call last):
  File "BubbleKern.py", line 57
    favDic = NSMutableDictionary.alloc().initWithDictionary_copyItems_(favDic, True)

**Comment by Tosche** [comment]
I updated the script to explicitly import NSMutableDictionary. Could you try the new version please?

**Comment by thommilson** [comment]
Perfect! Working fine now, thanks!
