### ISSUE TITLE
Unable to make bubble layers

### ISSUE THREAD

**Issue by skalyan91** [Tosche/BubbleKern#14]
When I try to run the “Make Bubble Layers” script, I get the following error:
```
Make Bubble Layers Error (MakeBubbleLayersMain): 'NSKVONotifying_GSApplication' object has no attribute 'displayDialog_withTitle_'
```

I am on Glyphs 3.2.2.

**Comment by skalyan91** [comment]
Turns out this is because I hadn’t entered any values for “Horizontal Offset” and “Vertical Offset”. Still, this is a bug, because it’s supposed to show a dialog box titled “Invalid Input” that says, “You typed something other than numbers in the text field.”.

**Comment by schriftgestalt** [comment]
I have worked on this a bit. I have send a pull request so that @Tosche can review what I did.

**Comment by skalyan91** [comment]
Thanks @schriftgestalt and @Tosche—that was quick! I’ve checked that the problem has been resolved.
